### ISSUE TITLE
README mentions stale URL

### ISSUE THREAD

**Issue by jwaldmann** [gereeter/bounded-intmap#3]
> The original idea, by Edward Kmett, is described here ( https://www.fpcomplete.com/user/edwardk/revisiting-matrix-multiplication/part-4 )

gives 404.  Apparently, this is https://www.schoolofhaskell.com/user/edwardk/revisiting-matrix-multiplication/part-4 now.

**Comment by gereeter** [comment]
Ah, somehow I'd missed this; sorry. Closed by #4.
